### PR TITLE
Added optional text to the loading spinner

### PR DESCRIPTION
**Pull request by abdullahranginwala**
https://github.com/citycoins/citycoin-ui/issues/97#issue-1046771712

Based on the feature suggested by @whoabuddy, optional text has been added to the loading spinner.

### CODE REVIEW

**Review by whoabuddy — CHANGES_REQUESTED** [review]
Hey @abdullahranginwala, thank you for the PR! There were a few things I'd change given the structure of the other components and how the spinner is loaded, and I left more detailed comments in the review.

I'd also love to see this implemented in one spot for testing, particularly this one sticks out to me because with this change, you could reduce it to just a `<LoadingSpinner text="blah blah blah" />` without using paragraph tags.

https://github.com/citycoins/citycoin-ui/blob/main/src/components/activation/RegisterUser.js#L262-L266

**Comment by whoabuddy** [comment]
Also, if you're in the CityCoins Discord we can chat about any of this in the #user-interface channel, I have the same user name there and I'm happy to help!

https://discord.gg/citycoins

**Comment by whoabuddy** [comment]
This looks great, last bit before merge, can you update the `activation/RegisterUser.js` component to use this at the bottom?

**Comment by abdullahranginwala** [comment]
@whoabuddy can you review the latest commit?

**Comment by whoabuddy** [comment]
Everything looks great, I did notice one small thing - on certain pages where the spinner is used in a box (like on [the activation page](http://localhost:3000/mia/activation?chain=mainnet)) the spinner loads left-justified and the content loads centered. I'll bet it has something to do with the CSS inheritance but overall a non-issue as loading in general could be improved (lots of spinners!).

**Review by whoabuddy — APPROVED** [review]

**Pull request merged**
